name: harbor

on:
  push:
    branches: main

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Login to harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.4.0
        with:
          registry: harbor.cyverse.org
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Cache Docker layers
        uses: actions/cache@v4.2.3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build and push bash
        id: docker_build_bash
        uses: docker/build-push-action@v6.16.0
        with:
          context: bash
          file: bash/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: harbor.cyverse.org/vice/cli/bash:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
     
      - name: Image digest bash
        run: echo ${{ steps.docker_build_bash.outputs.digest }}

      - name: Build and push gpu
        id: docker_build_gpu
        uses: docker/build-push-action@v6.16.0
        with:
          context: gpu
          file: gpu/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: harbor.cyverse.org/vice/cli/gpu:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Image digest gpu
        run: echo ${{ steps.docker_build_gpu.outputs.digest }}

      # Temp fix for cache growth
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache || true
